stages:
    - test

test_web:
    image: thecodingmachine/php:8.3-v4-cli
    stage: test
    services:
        -   name: mysql:8.0
            alias: mysql_tests
    variables:
        PHP_INI_MEMORY_LIMIT: "8G"
        PHP_EXTENSIONS: "intl gd"
        MYSQL_DATABASE: abenmada_backoffice_plugin_test
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
    script:
        - composer install --prefer-dist --no-ansi --no-scripts --no-interaction --no-progress
        - composer phpstan
        - composer cscheck
